FROM docker.getcollate.io/openmetadata/ingestion:1.4.0

USER root

ENV LANG=en_US.UTF-8 \
    TZ=Asia/Seoul \
    AIRFLOW_HOME=/opt/airflow

RUN apt-get update && apt-get install -y \
    git make gcc openssh-server \
    vim default-jdk

RUN echo "root:Ahqlwps12#$" | chpasswd && \
    echo "airflow:Ahqlwps12#$" | chpasswd && \
    mkdir -p /var/run/sshd /airflow/.ssh /root/.ssh && \
    echo "airflow   ALL=(ALL)   ALL" >> /etc/sudoers && \
    echo "alias vi=vim" >> /home/airflow/.bashrc

RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UseDNS no/UseDNS no/g' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

WORKDIR /home/airflow/workspace

EXPOSE 22

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
